# Generated by Django 3.1 on 2025-01-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20250125_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.TextField(default='Address', max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='City', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='Phone Number', max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='specialty',
            field=models.CharField(default='Specialty', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='waiting_time',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='working_hours',
            field=models.CharField(default='9:00 AM - 5:00 PM', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
