# Generated by Django 3.1 on 2025-01-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20250125_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='specialty',
            field=models.CharField(choices=[('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('pediatrics', 'Pediatrics'), ('orthopedics', 'Orthopedics'), ('dermatology', 'Dermatology'), ('dentistry', 'Dentistry'), ('psychiatry', 'Psychiatry'), ('general_surgery', 'General Surgery'), ('radiology', 'Radiology'), ('urology', 'Urology')], default='general_surgery', max_length=50),
        ),
    ]
