# Generated by Django 3.1 on 2025-01-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20250125_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('online_consultation', 'Online Consultation'), ('physical_therapy', 'Physical Therapy'), ('surgery', 'Surgery'), ('laboratory_tests', 'Laboratory Tests'), ('emergency_services', 'Emergency Services'), ('health_checkups', 'Health Checkups'), ('vaccination', 'Vaccination'), ('diet_advice', 'Diet Advice'), ('mental_health_support', 'Mental Health Support'), ('chronic_disease_management', 'Chronic Disease Management')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='services',
            field=models.ManyToManyField(blank=True, to='accounts.Service'),
        ),
    ]
