# Generated by Django 5.1.5 on 2025-01-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20250125_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'دكتور'), ('user', 'مستخدم عادي')], default='user', max_length=10, verbose_name='نوع الحساب'),
        ),
    ]
