# Generated by Django 5.1.5 on 2025-01-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_profile_name_alter_profile_who_i'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rating_count',
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, default='Default Name', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('doctor', 'دكتور'), ('user', 'مستخدم عادي')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='who_i',
            field=models.TextField(blank=True, default='Default Discription', max_length=500),
        ),
    ]
