# Generated by Django 5.1.5 on 2025-01-28 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_appointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='profile',
            new_name='doctor',
        ),
    ]
