# Generated by Django 5.1.5 on 2025-01-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_profile_appointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='available_times',
            field=models.JSONField(default=list),
        ),
    ]
