# Generated by Django 5.1.5 on 2025-01-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_profile_available_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='available_times',
            field=models.TextField(default=''),
        ),
    ]
