# Generated by Django 5.1.6 on 2025-02-06 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Default Name', max_length=50)),
                ('who_i', models.TextField(blank=True, default='Default Discription', max_length=500)),
                ('city', models.CharField(default='City', max_length=100)),
                ('address', models.TextField(default='Address', max_length=500)),
                ('phone', models.CharField(default='Phone Number', max_length=15)),
                ('working_hours', models.CharField(default='9:00 AM - 5:00 PM', max_length=100)),
                ('available_times', models.TextField(blank=True, default='', null=True)),
                ('waiting_time', models.IntegerField(default=15)),
                ('specialty', models.CharField(choices=[('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('pediatrics', 'Pediatrics'), ('orthopedics', 'Orthopedics'), ('dermatology', 'Dermatology'), ('dentistry', 'Dentistry'), ('psychiatry', 'Psychiatry'), ('general_surgery', 'General Surgery'), ('radiology', 'Radiology'), ('urology', 'Urology')], default='general_surgery', max_length=50)),
                ('services', models.TextField(blank=True, max_length=500, null=True)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(default='default_image.jpg', upload_to='images/')),
                ('facebook', models.URLField(blank=True, default='', null=True)),
                ('twitter', models.URLField(blank=True, default='', null=True)),
                ('linkedin', models.URLField(blank=True, default='', null=True)),
                ('instagram', models.URLField(blank=True, default='', null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('user_type', models.CharField(choices=[('doctor', 'دكتور'), ('user', 'مستخدم عادي')], default='user', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('appointment_time', models.DateTimeField()),
                ('confirmed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profile')),
            ],
        ),
    ]
