# Generated by Django 5.1.6 on 2025-02-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='specialty',
            field=models.CharField(choices=[('أطباء الأسنان', 'أطباء الأسنان'), ('أطباء القلب', 'أطباء القلب'), ('pediatrics', 'Pediatrics'), ('orthopedics', 'Orthopedics'), ('dermatology', 'Dermatology'), ('dentistry', 'Dentistry'), ('psychiatry', 'Psychiatry'), ('general_surgery', 'General Surgery'), ('radiology', 'Radiology'), ('urology', 'Urology')], default='general_surgery', max_length=50),
        ),
    ]
