# Generated by Django 5.1.6 on 2025-02-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='specialty',
            field=models.CharField(choices=[('أسنان', 'أسنان'), ('قلب', 'قلب'), ('جراحة العظام', 'جراحة العظام'), ('جلدية', 'جلدية'), ('نفسي', 'نفسي'), ('جراحة عامة', 'جراحة عامة'), ('أشعة', 'أشعة'), ('جراحة مسالك بولية', 'جراحة مسالك بولية')], default='general_surgery', max_length=50),
        ),
    ]
